services:
  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app 
    command: npm run dev 

  backend:
    environment:
      NODE_ENV: development
    ports:
      - '4001:4000' 
    volumes:
      - ./server:/app 
    command: sh -c "npm run migration:run && npm run dev"

  mysql:
    ports:
      - '3307:3306' 